package org.eduspace.backend.enums;

public enum NotificationType {
    SYSTEM,
    COURSE_APPROVAL,
    CREATOR_REQUEST,
    PEER_REVIEW,
    MENTOR_APPLICATION,
    WAITLIST_MILESTONE_REACHED,
    WAITLIST_READY_TO_START,
    WAITLIST_AUTO_START_REMINDER,
    WAITLIST_CANCELLED
}
